<?php
/**
 * Add metafields to portfolio CPT.
 *
 * @package           WritePoetry
 * @subpackage        WritePoetry/Base
 * @author            Giacomo Secchi <giacomo.secchi@gmail.com>
 * @copyright         2023 Giacomo Secchi
 * @license           GPL-2.0-or-later
 * @since             0.2.4
 */

namespace WritePoetry\Plugins\Translatepress;

use WritePoetry\Base\Base_Controller;
use WritePoetry\Api\Register_Custom_Fields;

/**
 * Class Testimonial
 *
 * @package WritePoetry\Plugins\Translatepress
 */
class Translatepress extends Base_Controller {
	/**
	 * Invoke hooks.
	 *
	 * @return void
	 */
	public function register() {
		add_filter( 'trp_get_url_for_language', array( $this, 'remove_end_slash_from_links' ), 10, 6 );
	}

	/**
	 * Remove trailing slashes from specific URLs.
	 *
	 * @param string $new_url              The new URL generated by TranslatePress.
	 * @param string $original_url         The original URL.
	 * @param string $language             The target language.
	 * @param string $abs_home             The absolute home URL.
	 * @param string $lang_from_url_string The language code from the URL.
	 * @param string $lang_url_slug        The language URL slug.
	 * @return string The modified URL.
	 */
	public function remove_end_slash_from_links( $new_url, $url, $language, $abs_home, $lang_from_url_string, $lang_url_slug ) {
		// Default URL patterns to check.
		$default_patterns  = array(
			'sitemap',
		);

		// Allow developers to add or modify URL patterns via a filter.
		$url_patterns = array_merge( $default_patterns, apply_filters( 'writepoetry_plugin_remove_end_slash_from_links', array() ) );

		// Check each pattern against the new URL.
		foreach ( $url_patterns  as $pattern ) {

			// Check if the URL is in the new URL.
			if ( false !== strpos( $new_url, $pattern ) ) {
				// Remove trailing slash if the pattern is found.
				return untrailingslashit( $new_url );
			}
		}

		// Return the original URL if no patterns match.
		return $new_url;
	}

}
